[project]
name = "python-avanzado"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyterlab>=4.5.6",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=2.4.4",
    "ruff>=0.15.12",
    "scikit-learn>=1.8.0",
    "sortedcontainers>=2.4.0",
    "toolz>=1.1.0",
]
